CREATE TABLE  `webcourses`.`courses` (
`course_id` INT NOT NULL AUTO_INCREMENT ,
`user_id` INT NOT NULL ,
`title` VARCHAR( 100 ) NOT NULL ,
`description` TEXT NOT NULL ,
`password` VARCHAR( 32 ) NOT NULL ,
`created_at` TIMESTAMP NOT NULL ,
`active` tinyint(1) NOT NULL,
PRIMARY KEY (  `course_id` )
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `webcourses`.`materials` (
  `material_id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `file` text,
  `org_file_name` text,
  `title` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `order_number` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`material_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `webcourses`.`groups` (
`group_id` INT NOT NULL AUTO_INCREMENT ,
`course_id` INT NOT NULL ,
`user_id` INT NOT NULL ,
`title` VARCHAR( 100 ) NOT NULL ,
`created_at` TIMESTAMP NOT NULL ,
PRIMARY KEY (  `group_id` )
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `webcourses`.`members` (
  `member_id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `added_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `course_id` int(11) NOT NULL,
  PRIMARY KEY (`member_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `webcourses`.`tests` (
  `test_id` int(11) NOT NULL AUTO_INCREMENT,
  `user` int(11) NOT NULL,
  `course` int(11) NOT NULL,
  `title` VARCHAR( 100 ) NOT NULL ,
  `created` TIMESTAMP NOT NULL DEFAULT 0,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `password` VARCHAR( 32 ) DEFAULT NULL,
  `time` int(11) NOT NULL,
  `visibility` tinyint(1) NOT NULL,
  `startDate` timestamp NOT NULL,
  `endDate` timestamp NOT NULL,
  `random` tinyint(1) DEFAULT NULL,
  `questionsCount` int(11) DEFAULT NULL,
  PRIMARY KEY (`test_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `webcourses`.`questions` (
  `question_id` int(11) NOT NULL AUTO_INCREMENT,
  `test` int(11) NOT NULL,
  `content` TEXT NOT NULL ,
  `type` VARCHAR( 100 ) NOT NULL,
  PRIMARY KEY (`question_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `webcourses`.`answers` (
  `answer_id` int(11) NOT NULL AUTO_INCREMENT,
  `question` int(11) NOT NULL,
  `content` TEXT NOT NULL ,
  `correct` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`answer_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `webcourses`.`countries` (
  `country_id` int(11) NOT NULL AUTO_INCREMENT,
  `Code` char(3) CHARACTER SET utf8 NOT NULL,
  `continent_id` tinyint(3) unsigned NOT NULL,
  `Name` char(52) CHARACTER SET utf8 NOT NULL,
  `Continent` enum('Asia','Europe','North America','Africa','Oceania','Antarctica','South America') CHARACTER SET utf8 NOT NULL DEFAULT 'Asia',
  `Region` char(26) CHARACTER SET utf8 NOT NULL,
  `LocalName` char(45) CHARACTER SET utf8 NOT NULL,
  `Capital` int(11) DEFAULT NULL,
  `Code2` char(2) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`country_id`),
  KEY `continent_id` (`continent_id`)
) ENGINE = INNODB;


CREATE TABLE IF NOT EXISTS `webcourses`.`test_results` (
  `testResult_id` int(11) NOT NULL AUTO_INCREMENT,
  `user` int(11) NOT NULL,
  `test` int(11) NOT NULL,
  `questionResult` int(11),
  `answerResult` int(11),
  `startDate` timestamp NOT NULL,
  `endDate` timestamp,
  PRIMARY KEY (`testResult_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `webcourses`.`answer_results` (
  `answerResult_id` int(11) NOT NULL AUTO_INCREMENT,
  `testResult` int(11),
  `answer` int(11) NOT NULL,
  PRIMARY KEY (`answerResult_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `webcourses`.`question_results` (
  `questionResult_id` int(11) AUTO_INCREMENT,
  `testResult` int(11),
  `question` int(11) NOT NULL,
  PRIMARY KEY (`questionResult_id`)
) ENGINE=InnoDB;

--
-- Zrzut danych tabeli `countries`
--

INSERT INTO `countries` (`Code`, `continent_id`, `Name`, `Continent`, `Region`, `LocalName`, `Capital`, `Code2`) VALUES
('AND', 4, 'Andorra', 'Europe', 'Southern Europe', 'Andorra', 55, 'AD'),
('ARE', 2, 'United Arab Emirates', 'Asia', 'Middle East', 'Al-Imarat al-A1Arabiya al-Muttahida', 65, 'AE'),
('AFG', 2, 'Afghanistan', 'Asia', 'Southern and Central Asia', 'Afganistan/Afqanestan', 1, 'AF'),
('ATG', 1, 'Antigua and Barbuda', 'North America', 'Caribbean', 'Antigua and Barbuda', 63, 'AG'),
('AIA', 1, 'Anguilla', 'North America', 'Caribbean', 'Anguilla', 62, 'AI'),
('ALB', 4, 'Albania', 'Europe', 'Southern Europe', 'ShqipA«ria', 34, 'AL'),
('ARM', 2, 'Armenia', 'Asia', 'Middle East', 'Hajastan', 126, 'AM'),
('ANT', 1, 'Netherlands Antilles', 'North America', 'Caribbean', 'Nederlandse Antillen', 33, 'AN'),
('AGO', 3, 'Angola', 'Africa', 'Central Africa', 'Angola', 56, 'AO'),
('ATA', 7, 'Antarctica', 'Antarctica', 'Antarctica', 'Â–', NULL, 'AQ'),
('ARG', 5, 'Argentina', 'South America', 'South America', 'Argentina', 69, 'AR'),
('ASM', 6, 'American Samoa', 'Oceania', 'Polynesia', 'Amerika Samoa', 54, 'AS'),
('AUT', 4, 'Austria', 'Europe', 'Western Europe', 'A–sterreich', 1523, 'AT'),
('AUS', 6, 'Australia', 'Oceania', 'Australia and New Zealand', 'Australia', 135, 'AU'),
('ABW', 1, 'Aruba', 'North America', 'Caribbean', 'Aruba', 129, 'AW'),
('AZE', 2, 'Azerbaijan', 'Asia', 'Middle East', 'AzA¤rbaycan', 144, 'AZ'),
('BIH', 4, 'Bosnia and Herzegovina', 'Europe', 'Southern Europe', 'Bosna i Hercegovina', 201, 'BA'),
('BRB', 1, 'Barbados', 'North America', 'Caribbean', 'Barbados', 174, 'BB'),
('BGD', 2, 'Bangladesh', 'Asia', 'Southern and Central Asia', 'Bangladesh', 150, 'BD'),
('BEL', 4, 'Belgium', 'Europe', 'Western Europe', 'BelgiA«/Belgique', 179, 'BE'),
('BFA', 3, 'Burkina Faso', 'Africa', 'Western Africa', 'Burkina Faso', 549, 'BF'),
('BGR', 4, 'Bulgaria', 'Europe', 'Eastern Europe', 'Balgarija', 539, 'BG'),
('BHR', 2, 'Bahrain', 'Asia', 'Middle East', 'Al-Bahrayn', 149, 'BH'),
('BDI', 3, 'Burundi', 'Africa', 'Eastern Africa', 'Burundi/Uburundi', 552, 'BI'),
('BEN', 3, 'Benin', 'Africa', 'Western Africa', 'BA©nin', 187, 'BJ'),
('BMU', 1, 'Bermuda', 'North America', 'North America', 'Bermuda', 191, 'BM'),
('BRN', 2, 'Brunei', 'Asia', 'Southeast Asia', 'Brunei Darussalam', 538, 'BN'),
('BOL', 5, 'Bolivia', 'South America', 'South America', 'Bolivia', 194, 'BO'),
('BRA', 5, 'Brazil', 'South America', 'South America', 'Brasil', 211, 'BR'),
('BHS', 1, 'Bahamas', 'North America', 'Caribbean', 'The Bahamas', 148, 'BS'),
('BTN', 2, 'Bhutan', 'Asia', 'Southern and Central Asia', 'Druk-Yul', 192, 'BT'),
('BVT', 7, 'Bouvet Island', 'Antarctica', 'Antarctica', 'BouvetA¸ya', NULL, 'BV'),
('BWA', 3, 'Botswana', 'Africa', 'Southern Africa', 'Botswana', 204, 'BW'),
('BLR', 4, 'Belarus', 'Europe', 'Eastern Europe', 'Belarus', 3520, 'BY'),
('BLZ', 1, 'Belize', 'North America', 'Central America', 'Belize', 185, 'BZ'),
('CAN', 1, 'Canada', 'North America', 'North America', 'Canada', 1822, 'CA'),
('CCK', 6, 'Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand', 'Cocos (Keeling) Islands', 2317, 'CC'),
('COD', 3, 'Congo, The Democratic Republic of the', 'Africa', 'Central Africa', 'RA©publique DA©mocratique du Congo', 2298, 'CD'),
('CAF', 3, 'Central African Republic', 'Africa', 'Central Africa', 'Centrafrique/BAa-AfrA®ka', 1889, 'CF'),
('COG', 3, 'Congo', 'Africa', 'Central Africa', 'Congo', 2296, 'CG'),
('CHE', 4, 'Switzerland', 'Europe', 'Western Europe', 'Schweiz/Suisse/Svizzera/Svizra', 3248, 'CH'),
('CIV', 3, 'CA´te dÂ’Ivoire', 'Africa', 'Western Africa', 'CA´te dÂ’Ivoire', 2814, 'CI'),
('COK', 6, 'Cook Islands', 'Oceania', 'Polynesia', 'The Cook Islands', 583, 'CK'),
('CHL', 5, 'Chile', 'South America', 'South America', 'Chile', 554, 'CL'),
('CMR', 3, 'Cameroon', 'Africa', 'Central Africa', 'Cameroun/Cameroon', 1804, 'CM'),
('CHN', 2, 'China', 'Asia', 'Eastern Asia', 'Zhongquo', 1891, 'CN'),
('COL', 5, 'Colombia', 'South America', 'South America', 'Colombia', 2257, 'CO'),
('CRI', 1, 'Costa Rica', 'North America', 'Central America', 'Costa Rica', 584, 'CR'),
('CUB', 1, 'Cuba', 'North America', 'Caribbean', 'Cuba', 2413, 'CU'),
('CPV', 3, 'Cape Verde', 'Africa', 'Western Africa', 'Cabo Verde', 1859, 'CV'),
('CXR', 6, 'Christmas Island', 'Oceania', 'Australia and New Zealand', 'Christmas Island', 1791, 'CX'),
('CYP', 2, 'Cyprus', 'Asia', 'Middle East', 'KA1pros/Kibris', 2430, 'CY'),
('CZE', 4, 'Czech Republic', 'Europe', 'Eastern Europe', 'A3esko', 3339, 'CZ'),
('DEU', 4, 'Germany', 'Europe', 'Western Europe', 'Deutschland', 3068, 'DE'),
('DJI', 3, 'Djibouti', 'Africa', 'Eastern Africa', 'Djibouti/Jibuti', 585, 'DJ'),
('DNK', 4, 'Denmark', 'Europe', 'Nordic Countries', 'Danmark', 3315, 'DK'),
('DMA', 1, 'Dominica', 'North America', 'Caribbean', 'Dominica', 586, 'DM'),
('DOM', 1, 'Dominican Republic', 'North America', 'Caribbean', 'RepAoblica Dominicana', 587, 'DO'),
('DZA', 3, 'Algeria', 'Africa', 'Northern Africa', 'Al-JazaÂ’ir/AlgA©rie', 35, 'DZ'),
('ECU', 5, 'Ecuador', 'South America', 'South America', 'Ecuador', 594, 'EC'),
('EST', 4, 'Estonia', 'Europe', 'Baltic Countries', 'Eesti', 3791, 'EE'),
('EGY', 3, 'Egypt', 'Africa', 'Northern Africa', 'Misr', 608, 'EG'),
('ESH', 3, 'Western Sahara', 'Africa', 'Northern Africa', 'As-Sahrawiya', 2453, 'EH'),
('ERI', 3, 'Eritrea', 'Africa', 'Eastern Africa', 'Ertra', 652, 'ER'),
('ESP', 4, 'Spain', 'Europe', 'Southern Europe', 'EspaA±a', 653, 'ES'),
('ETH', 3, 'Ethiopia', 'Africa', 'Eastern Africa', 'YeItyopA1iya', 756, 'ET'),
('FIN', 4, 'Finland', 'Europe', 'Nordic Countries', 'Suomi', 3236, 'FI'),
('FJI', 6, 'Fiji Islands', 'Oceania', 'Melanesia', 'Fiji Islands', 764, 'FJ'),
('FLK', 5, 'Falkland Islands', 'South America', 'South America', 'Falkland Islands', 763, 'FK'),
('FSM', 6, 'Micronesia, Federated States of', 'Oceania', 'Micronesia', 'Micronesia', 2689, 'FM'),
('FRO', 4, 'Faroe Islands', 'Europe', 'Nordic Countries', 'FA¸royar', 901, 'FO'),
('FRA', 4, 'France', 'Europe', 'Western Europe', 'France', 2974, 'FR'),
('GAB', 3, 'Gabon', 'Africa', 'Central Africa', 'Le Gabon', 902, 'GA'),
('GBR', 4, 'United Kingdom', 'Europe', 'British Islands', 'United Kingdom', 456, 'GB'),
('GRD', 1, 'Grenada', 'North America', 'Caribbean', 'Grenada', 916, 'GD'),
('GEO', 2, 'Georgia', 'Asia', 'Middle East', 'Sakartvelo', 905, 'GE'),
('GUF', 5, 'French Guiana', 'South America', 'South America', 'Guyane franA§aise', 3014, 'GF'),
('GHA', 3, 'Ghana', 'Africa', 'Western Africa', 'Ghana', 910, 'GH'),
('GIB', 4, 'Gibraltar', 'Europe', 'Southern Europe', 'Gibraltar', 915, 'GI'),
('GRL', 1, 'Greenland', 'North America', 'North America', 'Kalaallit Nunaat/GrA¸nland', 917, 'GL'),
('GMB', 3, 'Gambia', 'Africa', 'Western Africa', 'The Gambia', 904, 'GM'),
('GIN', 3, 'Guinea', 'Africa', 'Western Africa', 'GuinA©e', 926, 'GN'),
('GLP', 1, 'Guadeloupe', 'North America', 'Caribbean', 'Guadeloupe', 919, 'GP'),
('GNQ', 3, 'Equatorial Guinea', 'Africa', 'Central Africa', 'Guinea Ecuatorial', 2972, 'GQ'),
('GRC', 4, 'Greece', 'Europe', 'Southern Europe', 'EllA!da', 2401, 'GR'),
('SGS', 7, 'South Georgia and the South Sandwich Islands', 'Antarctica', 'Antarctica', 'South Georgia and the South Sandwich Islands', NULL, 'GS'),
('GTM', 1, 'Guatemala', 'North America', 'Central America', 'Guatemala', 922, 'GT'),
('GUM', 6, 'Guam', 'Oceania', 'Micronesia', 'Guam', 921, 'GU'),
('GNB', 3, 'Guinea-Bissau', 'Africa', 'Western Africa', 'GuinA©-Bissau', 927, 'GW'),
('GUY', 5, 'Guyana', 'South America', 'South America', 'Guyana', 928, 'GY'),
('HKG', 2, 'Hong Kong', 'Asia', 'Eastern Asia', 'Xianggang/Hong Kong', 937, 'HK'),
('HMD', 7, 'Heard Island and McDonald Islands', 'Antarctica', 'Antarctica', 'Heard and McDonald Islands', NULL, 'HM'),
('HND', 1, 'Honduras', 'North America', 'Central America', 'Honduras', 933, 'HN'),
('HRV', 4, 'Croatia', 'Europe', 'Southern Europe', 'Hrvatska', 2409, 'HR'),
('HTI', 1, 'Haiti', 'North America', 'Caribbean', 'HaA—ti/Dayti', 929, 'HT'),
('HUN', 4, 'Hungary', 'Europe', 'Eastern Europe', 'MagyarorszA!g', 3483, 'HU'),
('IDN', 2, 'Indonesia', 'Asia', 'Southeast Asia', 'Indonesia', 939, 'ID'),
('IRL', 4, 'Ireland', 'Europe', 'British Islands', 'Ireland/A‰ire', 1447, 'IE'),
('ISR', 2, 'Israel', 'Asia', 'Middle East', 'YisraÂ’el/IsraÂ’il', 1450, 'IL'),
('IND', 2, 'India', 'Asia', 'Southern and Central Asia', 'Bharat/India', 1109, 'IN'),
('IOT', 3, 'British Indian Ocean Territory', 'Africa', 'Eastern Africa', 'British Indian Ocean Territory', NULL, 'IO'),
('IRQ', 2, 'Iraq', 'Asia', 'Middle East', 'Al-A1Iraq', 1365, 'IQ'),
('IRN', 2, 'Iran', 'Asia', 'Southern and Central Asia', 'Iran', 1380, 'IR'),
('ISL', 4, 'Iceland', 'Europe', 'Nordic Countries', 'A?sland', 1449, 'IS'),
('ITA', 4, 'Italy', 'Europe', 'Southern Europe', 'Italia', 1464, 'IT'),
('JAM', 1, 'Jamaica', 'North America', 'Caribbean', 'Jamaica', 1530, 'JM'),
('JOR', 2, 'Jordan', 'Asia', 'Middle East', 'Al-Urdunn', 1786, 'JO'),
('JPN', 2, 'Japan', 'Asia', 'Eastern Asia', 'Nihon/Nippon', 1532, 'JP'),
('KEN', 3, 'Kenya', 'Africa', 'Eastern Africa', 'Kenya', 1881, 'KE'),
('KGZ', 2, 'Kyrgyzstan', 'Asia', 'Southern and Central Asia', 'Kyrgyzstan', 2253, 'KG'),
('KHM', 2, 'Cambodia', 'Asia', 'Southeast Asia', 'KAcmpuchA©a', 1800, 'KH'),
('KIR', 6, 'Kiribati', 'Oceania', 'Micronesia', 'Kiribati', 2256, 'KI'),
('COM', 3, 'Comoros', 'Africa', 'Eastern Africa', 'Komori/Comores', 2295, 'KM'),
('KNA', 1, 'Saint Kitts and Nevis', 'North America', 'Caribbean', 'Saint Kitts and Nevis', 3064, 'KN'),
('PRK', 2, 'North Korea', 'Asia', 'Eastern Asia', 'Choson Minjujuui InA1min Konghwaguk (Bukhan)', 2318, 'KP'),
('KOR', 2, 'South Korea', 'Asia', 'Eastern Asia', 'Taehan MinÂ’guk (Namhan)', 2331, 'KR'),
('KWT', 2, 'Kuwait', 'Asia', 'Middle East', 'Al-Kuwayt', 2429, 'KW'),
('CYM', 1, 'Cayman Islands', 'North America', 'Caribbean', 'Cayman Islands', 553, 'KY'),
('KAZ', 2, 'Kazakstan', 'Asia', 'Southern and Central Asia', 'Qazaqstan', 1864, 'KZ'),
('LAO', 2, 'Laos', 'Asia', 'Southeast Asia', 'Lao', 2432, 'LA'),
('LBN', 2, 'Lebanon', 'Asia', 'Middle East', 'Lubnan', 2438, 'LB'),
('LCA', 1, 'Saint Lucia', 'North America', 'Caribbean', 'Saint Lucia', 3065, 'LC'),
('LIE', 4, 'Liechtenstein', 'Europe', 'Western Europe', 'Liechtenstein', 2446, 'LI'),
('LKA', 2, 'Sri Lanka', 'Asia', 'Southern and Central Asia', 'Sri Lanka/Ilankai', 3217, 'LK'),
('LBR', 3, 'Liberia', 'Africa', 'Western Africa', 'Liberia', 2440, 'LR'),
('LSO', 3, 'Lesotho', 'Africa', 'Southern Africa', 'Lesotho', 2437, 'LS'),
('LTU', 4, 'Lithuania', 'Europe', 'Baltic Countries', 'Lietuva', 2447, 'LT'),
('LUX', 4, 'Luxembourg', 'Europe', 'Western Europe', 'Luxembourg/LA«tzebuerg', 2452, 'LU'),
('LVA', 4, 'Latvia', 'Europe', 'Baltic Countries', 'Latvija', 2434, 'LV'),
('LBY', 3, 'Libyan Arab Jamahiriya', 'Africa', 'Northern Africa', 'Libiya', 2441, 'LY'),
('MAR', 3, 'Morocco', 'Africa', 'Northern Africa', 'Al-Maghrib', 2486, 'MA'),
('MCO', 4, 'Monaco', 'Europe', 'Western Europe', 'Monaco', 2695, 'MC'),
('MDA', 4, 'Moldova', 'Europe', 'Eastern Europe', 'Moldova', 2690, 'MD'),
('MDG', 3, 'Madagascar', 'Africa', 'Eastern Africa', 'Madagasikara/Madagascar', 2455, 'MG'),
('MHL', 6, 'Marshall Islands', 'Oceania', 'Micronesia', 'Marshall Islands/Majol', 2507, 'MH'),
('MKD', 4, 'Macedonia', 'Europe', 'Southern Europe', 'Makedonija', 2460, 'MK'),
('MLI', 3, 'Mali', 'Africa', 'Western Africa', 'Mali', 2482, 'ML'),
('MMR', 2, 'Myanmar', 'Asia', 'Southeast Asia', 'Myanma Pye', 2710, 'MM'),
('MNG', 2, 'Mongolia', 'Asia', 'Eastern Asia', 'Mongol Uls', 2696, 'MN'),
('MAC', 2, 'Macao', 'Asia', 'Eastern Asia', 'Macau/Aomen', 2454, 'MO'),
('MNP', 6, 'Northern Mariana Islands', 'Oceania', 'Micronesia', 'Northern Mariana Islands', 2913, 'MP'),
('MTQ', 1, 'Martinique', 'North America', 'Caribbean', 'Martinique', 2508, 'MQ'),
('MRT', 3, 'Mauritania', 'Africa', 'Western Africa', 'Muritaniya/Mauritanie', 2509, 'MR'),
('MSR', 1, 'Montserrat', 'North America', 'Caribbean', 'Montserrat', 2697, 'MS'),
('MLT', 4, 'Malta', 'Europe', 'Southern Europe', 'Malta', 2484, 'MT'),
('MUS', 3, 'Mauritius', 'Africa', 'Eastern Africa', 'Mauritius', 2511, 'MU'),
('MDV', 2, 'Maldives', 'Asia', 'Southern and Central Asia', 'Dhivehi Raajje/Maldives', 2463, 'MV'),
('MWI', 3, 'Malawi', 'Africa', 'Eastern Africa', 'Malawi', 2462, 'MW'),
('MEX', 1, 'Mexico', 'North America', 'Central America', 'MA©xico', 2515, 'MX'),
('MYS', 2, 'Malaysia', 'Asia', 'Southeast Asia', 'Malaysia', 2464, 'MY'),
('MOZ', 3, 'Mozambique', 'Africa', 'Eastern Africa', 'MoA§ambique', 2698, 'MZ'),
('NAM', 3, 'Namibia', 'Africa', 'Southern Africa', 'Namibia', 2726, 'NA'),
('NCL', 6, 'New Caledonia', 'Oceania', 'Melanesia', 'Nouvelle-CalA©donie', 3493, 'NC'),
('NER', 3, 'Niger', 'Africa', 'Western Africa', 'Niger', 2738, 'NE'),
('NFK', 6, 'Norfolk Island', 'Oceania', 'Australia and New Zealand', 'Norfolk Island', 2806, 'NF'),
('NGA', 3, 'Nigeria', 'Africa', 'Western Africa', 'Nigeria', 2754, 'NG'),
('NIC', 1, 'Nicaragua', 'North America', 'Central America', 'Nicaragua', 2734, 'NI'),
('NLD', 4, 'Netherlands', 'Europe', 'Western Europe', 'Nederland', 5, 'NL'),
('NOR', 4, 'Norway', 'Europe', 'Nordic Countries', 'Norge', 2807, 'NO'),
('NPL', 2, 'Nepal', 'Asia', 'Southern and Central Asia', 'Nepal', 2729, 'NP'),
('NRU', 6, 'Nauru', 'Oceania', 'Micronesia', 'Naoero/Nauru', 2728, 'NR'),
('NIU', 6, 'Niue', 'Oceania', 'Polynesia', 'Niue', 2805, 'NU'),
('NZL', 6, 'New Zealand', 'Oceania', 'Australia and New Zealand', 'New Zealand/Aotearoa', 3499, 'NZ'),
('OMN', 2, 'Oman', 'Asia', 'Middle East', 'A1Uman', 2821, 'OM'),
('PAN', 1, 'Panama', 'North America', 'Central America', 'PanamA!', 2882, 'PA'),
('PER', 5, 'Peru', 'South America', 'South America', 'PerAo/Piruw', 2890, 'PE'),
('PYF', 6, 'French Polynesia', 'Oceania', 'Polynesia', 'PolynA©sie franA§aise', 3016, 'PF'),
('PNG', 6, 'Papua New Guinea', 'Oceania', 'Melanesia', 'Papua New Guinea/Papua Niugini', 2884, 'PG'),
('PHL', 2, 'Philippines', 'Asia', 'Southeast Asia', 'Pilipinas', 766, 'PH'),
('PAK', 2, 'Pakistan', 'Asia', 'Southern and Central Asia', 'Pakistan', 2831, 'PK'),
('POL', 4, 'Poland', 'Europe', 'Eastern Europe', 'Polska', 2928, 'PL'),
('SPM', 1, 'Saint Pierre and Miquelon', 'North America', 'North America', 'Saint-Pierre-et-Miquelon', 3067, 'PM'),
('PCN', 6, 'Pitcairn', 'Oceania', 'Polynesia', 'Pitcairn', 2912, 'PN'),
('PRI', 1, 'Puerto Rico', 'North America', 'Caribbean', 'Puerto Rico', 2919, 'PR'),
('PSE', 2, 'Palestine', 'Asia', 'Middle East', 'Filastin', 4074, 'PS'),
('PRT', 4, 'Portugal', 'Europe', 'Southern Europe', 'Portugal', 2914, 'PT'),
('PLW', 6, 'Palau', 'Oceania', 'Micronesia', 'Belau/Palau', 2881, 'PW'),
('PRY', 5, 'Paraguay', 'South America', 'South America', 'Paraguay', 2885, 'PY'),
('QAT', 2, 'Qatar', 'Asia', 'Middle East', 'Qatar', 2973, 'QA'),
('REU', 3, 'RA©union', 'Africa', 'Eastern Africa', 'RA©union', 3017, 'RE'),
('ROM', 4, 'Romania', 'Europe', 'Eastern Europe', 'RomAcnia', 3018, 'RO'),
('RUS', 4, 'Russian Federation', 'Europe', 'Eastern Europe', 'Rossija', 3580, 'RU'),
('RWA', 3, 'Rwanda', 'Africa', 'Eastern Africa', 'Rwanda/Urwanda', 3047, 'RW'),
('SAU', 2, 'Saudi Arabia', 'Asia', 'Middle East', 'Al-A1Arabiya as-SaA1udiya', 3173, 'SA'),
('SLB', 6, 'Solomon Islands', 'Oceania', 'Melanesia', 'Solomon Islands', 3161, 'SB'),
('SYC', 3, 'Seychelles', 'Africa', 'Eastern Africa', 'Sesel/Seychelles', 3206, 'SC'),
('SDN', 3, 'Sudan', 'Africa', 'Northern Africa', 'As-Sudan', 3225, 'SD'),
('SWE', 4, 'Sweden', 'Europe', 'Nordic Countries', 'Sverige', 3048, 'SE'),
('SGP', 2, 'Singapore', 'Asia', 'Southeast Asia', 'Singapore/Singapura/Xinjiapo/Singapur', 3208, 'SG'),
('SHN', 3, 'Saint Helena', 'Africa', 'Western Africa', 'Saint Helena', 3063, 'SH'),
('SVN', 4, 'Slovenia', 'Europe', 'Southern Europe', 'Slovenija', 3212, 'SI'),
('SJM', 4, 'Svalbard and Jan Mayen', 'Europe', 'Nordic Countries', 'Svalbard og Jan Mayen', 938, 'SJ'),
('SVK', 4, 'Slovakia', 'Europe', 'Eastern Europe', 'Slovensko', 3209, 'SK'),
('SLE', 3, 'Sierra Leone', 'Africa', 'Western Africa', 'Sierra Leone', 3207, 'SL'),
('SMR', 4, 'San Marino', 'Europe', 'Southern Europe', 'San Marino', 3171, 'SM'),
('SEN', 3, 'Senegal', 'Africa', 'Western Africa', 'SA©nA©gal/Sounougal', 3198, 'SN'),
('SOM', 3, 'Somalia', 'Africa', 'Eastern Africa', 'Soomaaliya', 3214, 'SO'),
('SUR', 5, 'Suriname', 'South America', 'South America', 'Suriname', 3243, 'SR'),
('STP', 3, 'Sao Tome and Principe', 'Africa', 'Central Africa', 'SALo TomA© e PrA­ncipe', 3172, 'ST'),
('SLV', 1, 'El Salvador', 'North America', 'Central America', 'El Salvador', 645, 'SV'),
('SYR', 2, 'Syria', 'Asia', 'Middle East', 'Suriya', 3250, 'SY'),
('SWZ', 3, 'Swaziland', 'Africa', 'Southern Africa', 'kaNgwane', 3244, 'SZ'),
('TCA', 1, 'Turks and Caicos Islands', 'North America', 'Caribbean', 'The Turks and Caicos Islands', 3423, 'TC'),
('TCD', 3, 'Chad', 'Africa', 'Central Africa', 'Tchad/Tshad', 3337, 'TD'),
('ATF', 7, 'French Southern territories', 'Antarctica', 'Antarctica', 'Terres australes franA§aises', NULL, 'TF'),
('TGO', 3, 'Togo', 'Africa', 'Western Africa', 'Togo', 3332, 'TG'),
('THA', 2, 'Thailand', 'Asia', 'Southeast Asia', 'Prathet Thai', 3320, 'TH'),
('TJK', 2, 'Tajikistan', 'Asia', 'Southern and Central Asia', 'ToA§ikiston', 3261, 'TJ'),
('TKL', 6, 'Tokelau', 'Oceania', 'Polynesia', 'Tokelau', 3333, 'TK'),
('TKM', 2, 'Turkmenistan', 'Asia', 'Southern and Central Asia', 'TA1rkmenostan', 3419, 'TM'),
('TUN', 3, 'Tunisia', 'Africa', 'Northern Africa', 'Tunis/Tunisie', 3349, 'TN'),
('TON', 6, 'Tonga', 'Oceania', 'Polynesia', 'Tonga', 3334, 'TO'),
('TMP', 2, 'East Timor', 'Asia', 'Southeast Asia', 'Timor Timur', 1522, 'TP'),
('TUR', 2, 'Turkey', 'Asia', 'Middle East', 'TA1rkiye', 3358, 'TR'),
('TTO', 1, 'Trinidad and Tobago', 'North America', 'Caribbean', 'Trinidad and Tobago', 3336, 'TT'),
('TUV', 6, 'Tuvalu', 'Oceania', 'Polynesia', 'Tuvalu', 3424, 'TV'),
('TWN', 2, 'Taiwan', 'Asia', 'Eastern Asia', 'TÂ’ai-wan', 3263, 'TW'),
('TZA', 3, 'Tanzania', 'Africa', 'Eastern Africa', 'Tanzania', 3306, 'TZ'),
('UKR', 4, 'Ukraine', 'Europe', 'Eastern Europe', 'Ukrajina', 3426, 'UA'),
('UGA', 3, 'Uganda', 'Africa', 'Eastern Africa', 'Uganda', 3425, 'UG'),
('UMI', 6, 'United States Minor Outlying Islands', 'Oceania', 'Micronesia/Caribbean', 'United States Minor Outlying Islands', NULL, 'UM'),
('USA', 1, 'United States', 'North America', 'North America', 'United States', 3813, 'US'),
('URY', 5, 'Uruguay', 'South America', 'South America', 'Uruguay', 3492, 'UY'),
('UZB', 2, 'Uzbekistan', 'Asia', 'Southern and Central Asia', 'Uzbekiston', 3503, 'UZ'),
('VAT', 4, 'Holy See (Vatican City State)', 'Europe', 'Southern Europe', 'Santa Sede/CittA  del Vaticano', 3538, 'VA'),
('VCT', 1, 'Saint Vincent and the Grenadines', 'North America', 'Caribbean', 'Saint Vincent and the Grenadines', 3066, 'VC'),
('VEN', 5, 'Venezuela', 'South America', 'South America', 'Venezuela', 3539, 'VE'),
('VGB', 1, 'Virgin Islands, British', 'North America', 'Caribbean', 'British Virgin Islands', 537, 'VG'),
('VIR', 1, 'Virgin Islands, U.S.', 'North America', 'Caribbean', 'Virgin Islands of the United States', 4067, 'VI'),
('VNM', 2, 'Vietnam', 'Asia', 'Southeast Asia', 'ViAat Nam', 3770, 'VN'),
('VUT', 6, 'Vanuatu', 'Oceania', 'Melanesia', 'Vanuatu', 3537, 'VU'),
('WLF', 6, 'Wallis and Futuna', 'Oceania', 'Polynesia', 'Wallis-et-Futuna', 3536, 'WF'),
('WSM', 6, 'Samoa', 'Oceania', 'Polynesia', 'Samoa', 3169, 'WS'),
('YEM', 2, 'Yemen', 'Asia', 'Middle East', 'Al-Yaman', 1780, 'YE'),
('MYT', 3, 'Mayotte', 'Africa', 'Eastern Africa', 'Mayotte', 2514, 'YT'),
('YUG', 4, 'Yugoslavia', 'Europe', 'Southern Europe', 'Jugoslavija', 1792, 'YU'),
('ZAF', 3, 'South Africa', 'Africa', 'Southern Africa', 'South Africa', 716, 'ZA'),
('ZMB', 3, 'Zambia', 'Africa', 'Eastern Africa', 'Zambia', 3162, 'ZM'),
('ZWE', 3, 'Zimbabwe', 'Africa', 'Eastern Africa', 'Zimbabwe', 4068, 'ZW');